Epic 1987 Barcode Scanner Classical Component
doo/scanbot-barcode-scanner-sdk-example-flutter pull request #22
Opened 2022-06-28 10:26 UTC by Sarbjyotsingh

2022-06-30 07:42 UTC, marcosaia1812 requested changes
Looks good 👍🏻 Again, just left a micro comment for a micro change

2022-06-30 07:42 UTC, marcosaia1812 commented on lib/main.dart
> +            'Scan Barcode custom ui',
I'd change it to Scan Barcode (Custom UI) or something like this. The main thing is "ui" should be "UI"

2022-06-30 08:49 UTC, 4BooM04 approved these changes

2022-06-30 08:49 UTC, 4BooM04 commented on lib/main.dart
> +            'Scan Barcode custom ui',
lets make this for both examples

2022-06-30 08:52 UTC, Sarbjyotsingh commented on lib/main.dart
> +            'Scan Barcode custom ui',
Resolved

2022-06-30 08:53 UTC, marcosaia1812 approved these changes

2022-07-18 10:28 UTC, hudson-pierce commented
run tests android

2022-07-22 12:42 UTC, merged